### ISSUE TITLE
bug - event summary page not loading - failing on json

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#321]
http://www.affinity.works/groups/3/events/9

The user can see the group for RSVP but can't for the non-attendances version. 

Navigated to http://www.affinity.works/groups/3/events/9
application-e686156….js:19 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at t.value (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:19:12643)
    at t.value (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:19:13720)
    at d._renderValidatedComponentWithoutOwnerOrContext (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:24:17303)
    at d._renderValidatedComponent (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:24:17430)
    at d._updateRenderedComponent (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:24:16730)
    at d._performComponentUpdate (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:24:16531)
    at d.updateComponent (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:24:15809)
    at d.receiveComponent (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:24:14920)
    at Object.receiveComponent (http://www.affinity.works/assets/application-e68615669b30434d65c4c10356b114dce1eb66e913d32404c9ab18c55ad275bf.js:5:29897)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8598:20)
value @ application-e686156….js:19
value @ application-e686156….js:19
_renderValidatedComponentWithoutOwnerOrContext @ application-e686156….js:24
_renderValidatedComponent @ application-e686156….js:24
_updateRenderedComponent @ application-e686156….js:24
_performComponentUpdate @ application-e686156….js:24
updateComponent @ application-e686156….js:24
receiveComponent @ application-e686156….js:24
receiveComponent @ application-e686156….js:5
obj.(anonymous function) @ backend.js:8598
_updateRenderedComponent @ application-e686156….js:24
_performComponentUpdate @ application-e686156….js:24
updateComponent @ application-e686156….js:24
performUpdateIfNecessary @ application-e686156….js:24
performUpdateIfNecessary @ application-e686156….js:5
obj.(anonymous function) @ backend.js:8598
s @ application-e686156….js:3
perform @ application-e686156….js:6
perform @ application-e686156….js:6
perform @ application-e686156….js:3
E @ application-e686156….js:3
closeAll @ application-e686156….js:6
perform @ application-e686156….js:6
batchedUpdates @ application-e686156….js:17
u @ application-e686156….js:3
r @ application-e686156….js:7
enqueueSetState @ application-e686156….js:7
r.setState @ application-e686156….js:7
d.onStateChange @ application-e686156….js:18
d @ application-e686156….js:18
(anonymous) @ application-e686156….js:27
(anonymous) @ application-e686156….js:27
dispatch @ application-e686156….js:27
a.isFSA.n.payload.then.o.payload @ application-e686156….js:27
Navigated to http://www.affinity.works/groups/3/events/9/attendances

**Comment by matinieves** [comment]
@rabble which user are you using?

**Comment by rabble** [comment]
335 which is the organizer for that group.

**Comment by Matt-Holland** [comment]
this seems fixed. closing.
